name: Discord Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check files
        run: |
          pwd
          ls -la

      - name: Install packages
        run: npm install

      - name: Install packages
        run: npm install

      - name: Start bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: node index.js
